---
- name: Create different directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0700'
    state: directory
  loop:
    - ~/.config
    - ~/.local
    - ~/.ssh/
    - ~/.config/ghostty

- name: Setup symlinks
  ansible.builtin.file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: link
    force: true
  loop: "{{ dotfiles_add_symlinks }}"
