---
- name: Clone tmux plugin manager tpm
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"

- name: Install tmux plugins
  ansible.builtin.shell: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: ~/.tmux/plugins/
  changed_when: false

- name: Manually install catppucin theme
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/tmux.git"
    dest: "~/.config/tmux/plugins/catppuccin"
    version: "latest"

